name: Dart CI with Flutter 3.16.9

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      flutter:
        image: cirrusci/flutter:3.16.9
        ports:
          - 8080:8080
          - 8081:8081
          - 9222:9222
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: docker exec -t flutter flutter pub get

    - name: Run tests
      run: docker exec -t flutter flutter test
