name: Dart CI with Flutter 3.16.9

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Flutter
      run: |
        git clone --branch 3.16.9 https://github.com/flutter/flutter.git
        export PATH="$PATH:`pwd`/flutter/bin"

    - name: Verify Flutter installation
      run: flutter --version

    - name: Accept Flutter licenses
      run: flutter doctor --android-licenses

    - name: Run flutter doctor
      run: flutter doctor -v

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
    
      run: flutter test
